[project]
name = "executorch-tiled-inference"
version = "0.1.0"
description = "ExecutorTorch Multi-Model Tiled Inference Demo"
requires-python = ">=3.8"
dependencies = [
    "torch",
    "executorch",
    "torchvision",
]

[tool.ruff]
line-length = 100
